name: Events

on:
  push:
    branches:
      - main
    paths:
      - "events/**"
  pull_request:
    paths:
      - "events/**"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: events

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --check

  linting:
    name: Linting
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo clippy --all-features -- --deny warnings

  testing:
    name: Testing
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test --all-features

  building:
    name: Building
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release --all-features

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: events
          path: events/target/release/events
